load("//bazel:spu.bzl", "spu_cc_binary")

spu_cc_binary(
    name = "op_bench",
    srcs = ["op_bench.cc"],
    deps = [
        "//libspu/core:context",
        "//libspu/core:value",
        "//libspu/core:pt_buffer_view",
        "//libspu:spu_cc_proto",
        "//libspu/mpc/cheetah:protocol",
        "//libspu/kernel/hal:polymorphic",
        "//libspu/kernel/hal:constants",
        "//libspu/kernel/hal:public_helper",
        "//libspu/kernel/hal:type_cast",
        "//libspu/kernel/hal:shape_ops",
        "//libspu/kernel/hal/intrinsic/nn:activation",
        "@yacl//yacl/link",
    ],
)
